apiVersion: v1
kind: Secret
metadata:
  name: xapisecrets
type: Opaque
stringData: 
  MailJetPublicAPIKEY: $MailJetPublicAPIKEY
  MailJetPrivateSecret: $MailJetPrivateSecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eg-notification
  template:
    metadata:
      labels:
        app: eg-notification
    spec:
      containers:
      - image: inftfg2021/eg.notification:$TAG
        name: eg-notification
        env: 
          - name: FLASK_ENV
            value: $ENV
          - name: FLASK_APP
            value: app
          - name: FLASK_RUN_HOST
            value: "0.0.0.0"
          - name: EMAIL_SENDER
            value: $EMAILSENDER
          - name: MJ_APIKEY_PUBLIC
            valueFrom:
              secretKeyRef:
                name: xapisecrets
                key: MailJetPublicAPIKEY
          - name: MJ_APIKEY_PRIVATE
            valueFrom:
              secretKeyRef:
                name: xapisecrets
                key: MailJetPrivateSecret
---
apiVersion: v1
kind: Service
metadata:
  name: eg-notification
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "eg-notification"
    port: 5000
  selector:
    app: eg-notification
